backend:
  name: github
  repo: marchollinger/next-test
  # api_root: https://api.github.com
  # base_url: https://api.netlify.com
  # auth_endpoint: auth
media_folder: "public/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads"
collections:
  - name: "recipe" # Used in routes, e.g., /admin/collections/blog
    label: "Recipe" # Used in the UI
    folder: "recipes/recipe" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Preparation Time",
          name: "prep_time",
          widget: "number",
          value_type: "int",
          min: 5,
          step: 5,
        }
      - {
          label: "Cook Time",
          name: "cook_time",
          widget: "number",
          value_type: "int",
          min: 5,
          step: 5,
        }
      - { label: "Image", name: "image", widget: "image", choose_url: true }
      - { label: "Body", name: "body", widget: "markdown" }
